## ndarray 생성하기 출력

In [1]:
# numpy 모듈을 옵니다.
import numpy as np

# 1차원 형태 / 벡터(Vector)
data_1 = [1, 2, 3, 4, 5]

# 2차원 형태 / 행렬(Matrix)
data_2 = [[1, 2, 3], 
          [4, 5, 6]]

data_3 = [[1., 2, 3.0], 
          [4, 5.0, 6]]

vector_1 = np.array(data_1)
matrix_1 = np.array(data_2)
matrix_2 = np.array(data_3)

matrix_3 = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7 ,8, 9]])

print("vector_1: ", vector_1)
print("matrix_1: ", matrix_1)
print("matrix_2: ", matrix_2)
print("matrix_3: ", matrix_3)

vector_1:  [1 2 3 4 5]
matrix_1:  [[1 2 3]
 [4 5 6]]
matrix_2:  [[1. 2. 3.]
 [4. 5. 6.]]
matrix_3:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


## ndarray - 배열 생성 함수들 출력

In [2]:
print("1) np.zeros(5): ", np.zeros(5))
print("2) np.zeors((2,5)): ", np.zeros((2,5)))
print("3) np.ones(5): ", np.ones(5))
print("4) np.empty((2,2,3)) :", np.empty((2, 2, 3 ))) # empty 함수는 크기만 지정한 후 임의의 값이 채워진다.
print("5) np.arange(5) :", np.arange(5))
print("6) np.full((3, 3),7): \n", np.full((3, 3),7)) # full 함수는 특정 값으로 배열 크기와 매개변수를 채울 수 있댜.

1) np.zeros(5):  [0. 0. 0. 0. 0.]
2) np.zeors((2,5)):  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3) np.ones(5):  [1. 1. 1. 1. 1.]
4) np.empty((2,2,3)) : [[[2.68156159e+154 2.68156159e+154 6.92988821e-310]
  [6.92988275e-310 6.92988791e-310 0.00000000e+000]]

 [[6.92988467e-310 0.00000000e+000 0.00000000e+000]
  [4.94065646e-324 0.00000000e+000 6.36598738e-314]]]
5) np.arange(5) : [0 1 2 3 4]
6) np.full((3, 3),7): 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


## ndarray - 정보 확인 출력

In [3]:
# 내장 type 함수를 통해 ndarray type 확인
print(type(vector_1))

# dtype: 타입을 알려줍니다.
print(vector_1.dtype)
print(matrix_1.dtype)
print(matrix_2.dtype)
print(matrix_3.dtype)

# ndim: 차원을 알려줍니다.
print(vector_1.ndim)
print(matrix_1.ndim)
print(matrix_2.ndim)
print(matrix_3.ndim)

# shape: 행렬의 크기를 알려줍니다.
print(vector_1.shape)
print(matrix_1.shape)
print(matrix_2.shape)
print(matrix_3.shape)

# size: 행렬의 개수를 알려줍니다. 
print(vector_1.size)
print(matrix_1.size)
print(matrix_2.size)
print(matrix_3.size)

<class 'numpy.ndarray'>
int64
int64
float64
int64
1
2
2
2
(5,)
(2, 3)
(2, 3)
(3, 3)
5
6
6
9


## ndarray - dtype 함수 출력

In [4]:
vec_dtype = np.array([1, 2, 3, 4, 5], dtype=np.int64)
matrix_dtype = np.array([[1,2,3],
                        [4,5,6]], dtype=np.float64)

print("vec_dtype: ", vec_dtype.dtype, vec_dtype, )
print("matrix_dtype: ", matrix_dtype.dtype, matrix_dtype)

vec_dtype:  int64 [1 2 3 4 5]
matrix_dtype:  float64 [[1. 2. 3.]
 [4. 5. 6.]]


## ndaaray - astype 함수 출력

In [5]:
# 부동소수점 to 정수형
arr_float_1 = np.array([1.3, 2.3, 3.2, 4.9, 5.1], dtype=np.float64)
print(arr_float_1.dtype, ": ", arr_float_1)
arr_int = arr_float_1.astype(np.int64)
print(arr_int.dtype, ": ", arr_int)

# 문자열 to 부동소수점
arr_str = np.array(["1.37", "-7.3", "3.14", "7.79"], dtype=np.string_)
print(arr_str.dtype, ": ", arr_str)
# astype(float)으로 줄 경우 파이썬이 적절한 타입으로 정해준다.
arr_float_2 = arr_str.astype(float)
print(arr_float_2.dtype, ": ", arr_float_2)

float64 :  [1.3 2.3 3.2 4.9 5.1]
int64 :  [1 2 3 4 5]
|S4 :  [b'1.37' b'-7.3' b'3.14' b'7.79']
float64 :  [ 1.37 -7.3   3.14  7.79]


## 인덱싱(Indexing)출력

In [6]:
# numpy 모듈을 옵니다.
import numpy as np

# 1차원 형태
vector_1 = np.array([1, 2, 3, 4, 5])

# 2차원 형태
matrix_2 = np.array([[1, 2, 3, 4, 5], 
                     [6, 7, 8, 9, 10], 
                     [11, 12, 13, 14, 15], 
                     [16, 17, 18, 19, 20], 
                     [21, 22, 23, 24, 25]]) 
                     
# 1차원 형태 - 인덱싱
print("vector_1[1]: ", vector_1[1])
print("vector_1[-1]: ", vector_1[-1])   

# 2차원 형태 - 인덱싱
print("matrix_2[1, 1]: ", matrix_2[1, 1])
print("matrix_2[2, -1]: ", matrix_2[2, -1])

vector_1[1]:  2
vector_1[-1]:  5
matrix_2[1, 1]:  7
matrix_2[2, -1]:  15


## 슬라이싱(Slicing) - 1차원 출력

In [7]:
# numpy 모듈을 옵니다.
import numpy as np

# 1차원 형태
vector = np.array([1, 2, 3, 4, 5])

print(vector[:])
print(vector[:4])
print(vector[1:3])
print(vector[2:])
print(vector[2:-1])

[1 2 3 4 5]
[1 2 3 4]
[2 3]
[3 4 5]
[3 4]


## 슬라이싱(Slicing) - 2차원 출력

In [8]:
# numpy 모듈을 옵니다.
import numpy as np

# 2차원 형태
matrix = np.array([[1, 2, 3, 4, 5], 
                     [6, 7, 8, 9, 10], 
                     [11, 12, 13, 14, 15], 
                     [16, 17, 18, 19, 20], 
                     [21, 22, 23, 24, 25]]) 

print(matrix[:2, 3:], matrix[:2, 3:].shape)

print(matrix[4], matrix[4].shape)
print(matrix[4, :], matrix[4, :].shape)
print(matrix[4:,:], matrix[4:,:].shape)

print(matrix[:, :2], matrix[:, :2].shape)

print(matrix[1, :2], matrix[1, :2].shape)
print(matrix[1:2, :2], matrix[1:2, :2].shape)

[[ 4  5]
 [ 9 10]] (2, 2)
[21 22 23 24 25] (5,)
[21 22 23 24 25] (5,)
[[21 22 23 24 25]] (1, 5)
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]] (5, 2)
[6 7] (2,)
[[6 7]] (1, 2)


## 통계 및 수학 함수 출력

In [9]:
# 2차원 형태
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print("합 :",  np.sum(matrix))    # 합
print("합 :", matrix.sum())       # 합
print("평균: ", matrix.mean())     # 평균
print("평균: ", np.mean(matrix))   # 평균
print("표준편차 :", np.std(matrix)) # 표준 편차
print("분산: ", np.var(matrix))    # 분산 
print("최대값: ", np.max(matrix))   # 최대값
print("최소값: ", np.min(matrix))   # 최소값

# 열과 행에서 최대값, 최솟값 찾을 경우
# 열에서 찾기
print("열에서 최대값 :", np.max(matrix, axis=0))  # 열에서 최대값
print("열에서 최소값 :", np.min(matrix, axis=0))  # 열에서 최소값
print("열에서 평균값 :", np.mean(matrix, axis=0)) # 열에서 평균값

# 행에서 찾기
print("행에서 최대값 :", np.max(matrix, axis=1))  # 행에서 최대값
print("행에서 최소값 :", np.min(matrix, axis=1))  # 행에서 최소값
print("행에서 평균값 :", np.mean(matrix, axis=1)) # 행에서 평균값

합 : 45
합 : 45
평균:  5.0
평균:  5.0
표준편차 : 2.581988897471611
분산:  6.666666666666667
최대값:  9
최소값:  1
열에서 최대값 : [7 8 9]
열에서 최소값 : [1 2 3]
열에서 평균값 : [4. 5. 6.]
행에서 최대값 : [3 6 9]
행에서 최소값 : [1 4 7]
행에서 평균값 : [2. 5. 8.]


## 난수 생성 함수들 출력

In [10]:
# 난수 생성
# 초기값 설정
np.random.seed(0)

print("0과 1.0 사이에서 10개의 실수 난수 생성: ", np.random.random(10))
print("1부터 45 사이에 6개 정수를 생성합니다. (로또 와 동일): ", np.random.randint(0, 46, 6))
print("평균이 0.0 이고 표준편차가 1.0인 정규분포에서 5개의 수를 뽑음: ", np.random.normal(0.0, 1.0, 5))
print("1.0 보다 크고 5.0 보다 작은 5개의 수를 뽑습니다. : ", np.random.uniform(1.0, 5.0, 5))

print("0.0 ~ 1.0 사이 3개의 실수를 랜덤으로 생성합니다.(random_sample) : \n", np.random.random_sample((3,3)))
print("0.0 ~ 1.0 사이 3개의 실수를 랜덤으로 생성합니다.(uniform) : \n", np.random.uniform(0.0, 1.0, (3,3)))
print("0.0 ~ 1.0 사이 3개의 실수를 랜덤으로 생성합니다.(rand) : \n", np.random.rand(3,3))

print("정규분포의 난수 생성(평균이 0이고 표준편차가 1인 난수 생성,standard_normal) : \n", np.random.standard_normal((3,3)))
print("정규분포의 난수 생성(평균이 0이고 표준편차가 1인 난수 생성,normal) : \n", np.random.normal(0.0, 1.0,(3,3)))
print("정규분포의 난수 생성(평균이 0이고 표준편차가 1인 난수 생성,randn) : \n", np.random.randn(3,3))

print("1 ~ 3 사이에서 랜덤하게 샘플을 선택합니다. : ", np.random.choice([1,2,3], 3))

# shuffle 함수는 배열을 무작위로 섞는다.
vector = [1,2,3,4,5]
np.random.shuffle(vector)
print("shuffle 함수로 무작위로 섞음: ", vector)

0과 1.0 사이에서 10개의 실수 난수 생성:  [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
1부터 45 사이에 6개 정수를 생성합니다. (로또 와 동일):  [38 39 23 24 17 37]
평균이 0.0 이고 표준편차가 1.0인 정규분포에서 5개의 수를 뽑음:  [-0.470771    0.973016   -1.27814912  1.43737068 -0.07770457]
1.0 보다 크고 5.0 보다 작은 5개의 수를 뽑습니다. :  [4.20364301 3.08190992 3.71551812 3.88253062 3.32807917]
0.0 ~ 1.0 사이 3개의 실수를 랜덤으로 생성합니다.(random_sample) : 
 [[0.53737323 0.75861562 0.10590761]
 [0.47360042 0.18633234 0.73691818]
 [0.21655035 0.13521817 0.32414101]]
0.0 ~ 1.0 사이 3개의 실수를 랜덤으로 생성합니다.(uniform) : 
 [[0.14967487 0.22232139 0.38648898]
 [0.90259848 0.44994999 0.61306346]
 [0.90234858 0.09928035 0.96980907]]
0.0 ~ 1.0 사이 3개의 실수를 랜덤으로 생성합니다.(rand) : 
 [[0.65314004 0.17090959 0.35815217]
 [0.75068614 0.60783067 0.32504723]
 [0.03842543 0.63427406 0.95894927]]
정규분포의 난수 생성(평균이 0이고 표준편차가 1인 난수 생성,standard_normal) : 
 [[ 1.08963016  1.25441407  1.41910204]
 [-0.74385608 -2.5174371  -1.50709602]
 [ 1

## 정렬 - sort() 출력

In [11]:
# 난수 생성기의 시드값에 따라 정해진 난수를 생성
np.random.seed(1)

# 표준편차가 1이, 평균값이 0인 정규분포에서 랜덤으로 숫자를 결정
# 1차원
vector = np.random.randn(5)

print("1차원 배열 sort() 정렬 전: ", vector)
vector.sort()
print("1차원 배열 sort() 정렬 후: ", vector)

# 2차원
matrix_1 = np.random.randn(5, 5)
print("2차원 배열 sort() 정렬 전: \n", matrix_1)
matrix_1.sort()
print("2차원 배열 sort() 정렬 후: \n", matrix_1)

# 특정 축을 기준으로 정렬
matrix_2 = np.random.randn(5, 5)
print("2차원 배열 axis=0 축 기준 정렬 전: \n", matrix_2)
matrix_2.sort(axis=0)
print("2차원 배열 axis=0 축 기준 정렬 후: \n", matrix_2)

matrix_3 = np.random.randn(5, 5)
print("2차원 배열 axis=1 축 기준 정렬 전: \n", matrix_3)
matrix_3.sort(axis=1)
print("2차원 배열 axis=1 축 기준 정렬 후: \n", matrix_3)

# 첫 번째 행만 정렬
matrix_4 = np.random.randn(5, 5)
print("2차원 배열 첫 번째 행만 정렬 전: \n", matrix_4)
matrix_4[:,0].sort()
print("2차원 배열 첫 번째 행만 정렬 후: \n", matrix_4)

1차원 배열 sort() 정렬 전:  [ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
1차원 배열 sort() 정렬 후:  [-1.07296862 -0.61175641 -0.52817175  0.86540763  1.62434536]
2차원 배열 sort() 정렬 전: 
 [[-2.3015387   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595]
 [-0.68372786 -0.12289023 -0.93576943 -0.26788808  0.53035547]]
2차원 배열 sort() 정렬 후: 
 [[-2.3015387  -0.7612069  -0.24937038  0.3190391   1.74481176]
 [-2.06014071 -0.38405435 -0.3224172   1.13376944  1.46210794]
 [-1.09989127 -0.87785842 -0.17242821  0.04221375  0.58281521]
 [-1.10061918  0.50249434  0.90085595  0.90159072  1.14472371]
 [-0.93576943 -0.68372786 -0.26788808 -0.12289023  0.53035547]]
2차원 배열 axis=0 축 기준 정렬 전: 
 [[-0.69166075 -0.39675353 -0.6871727  -0.84520564 -0.67124613]
 [-0.0126646  -1.11731035  0.2344157   1.65980218  0.74204416]
 [-0.

## 정렬 - argsort()출력

In [12]:
np.random.seed(2)

# 2차원 배열을 생성합니다.
matrix = np.random.randn(5, 5)
print("랜덤으로 생성된 2차원 배열: \n", matrix)

# 기준이 되는 1차원 배열을 생성합니다.
vector = np.array([5, 3, 1, 2, 4])

# matrix 배열에 첫번째 열에 vector 배열의 요소값을 넣어줍니다.
matrix[0] = vector
print("matrix 배열에 첫번째 열에 vector 배열의 요소값 대입: \n", matrix)
print("argsort()로 정렬 된 배열: \n", matrix[:, matrix[0].argsort()])

랜덤으로 생성된 2차원 배열: 
 [[-0.41675785 -0.05626683 -2.1361961   1.64027081 -1.79343559]
 [-0.84174737  0.50288142 -1.24528809 -1.05795222 -0.90900761]
 [ 0.55145404  2.29220801  0.04153939 -1.11792545  0.53905832]
 [-0.5961597  -0.0191305   1.17500122 -0.74787095  0.00902525]
 [-0.87810789 -0.15643417  0.25657045 -0.98877905 -0.33882197]]
matrix 배열에 첫번째 열에 vector 배열의 요소값 대입: 
 [[ 5.          3.          1.          2.          4.        ]
 [-0.84174737  0.50288142 -1.24528809 -1.05795222 -0.90900761]
 [ 0.55145404  2.29220801  0.04153939 -1.11792545  0.53905832]
 [-0.5961597  -0.0191305   1.17500122 -0.74787095  0.00902525]
 [-0.87810789 -0.15643417  0.25657045 -0.98877905 -0.33882197]]
argsort()로 정렬 된 배열: 
 [[ 1.          2.          3.          4.          5.        ]
 [-1.24528809 -1.05795222  0.50288142 -0.90900761 -0.84174737]
 [ 0.04153939 -1.11792545  2.29220801  0.53905832  0.55145404]
 [ 1.17500122 -0.74787095 -0.0191305   0.00902525 -0.5961597 ]
 [ 0.25657045 -0.98877905 -0.1564341

## 배열의 크기 바꾸기 reshape()출력

In [13]:
# (5 , 4)
data = [[1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9 ,10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]

matrix = np.array(data)
print("matrix.shape: ",  matrix.shape)

print("matrix.reshape(2,10): \n", matrix.reshape(2,10))

# 주의사항, 배열의 크기를 변경할 때 행과 열의 개수는 동일해야 합니다. 
# 따라서 size를 함수를 사용해서 크기를 먼저 확인합니다.
print("matrix.size: ", matrix.size)

# reshape 자주 사용 되는 -1 매개변수는 해당하는 열의 개수의 맞게끔 변경해줍니다.
print("reshape(1, -1): \n", matrix.reshape(1, -1))
print("reshape(2, -1): \n", matrix.reshape(2, -1))
print("reshape(4, -1): \n", matrix.reshape(4, -1))
print("reshape(5, -1): \n", matrix.reshape(5, -1))

# 1차원 배열로 변경 해줌
print("reshape(-1): \n", matrix.reshape(-1))

matrix.shape:  (5, 4)
matrix.reshape(2,10): 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
matrix.size:  20
reshape(1, -1): 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
reshape(2, -1): 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
reshape(4, -1): 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
reshape(5, -1): 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
reshape(-1): 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 벡터나 행렬 전치하기(transpose, swapaxes)출력

In [14]:
# (5 , 4)
data = [[1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9 ,10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]

matrix = np.array(data)

print("matrix: \n", matrix)
print("matrix.T : \n", matrix.T)
print("matrix.transpose(): \n", matrix.transpose())
print("np.transpose(matrix): \n", np.transpose(matrix))
print("matrix.swapaxes(0, 1): \n", matrix.swapaxes(0, 1))
print("np.swapaxes(matrix, 0, 1): \n", np.swapaxes(matrix, 0, 1))
print("matrix 데이터는 복사되지 않았습니다: \n", matrix)

matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
matrix.T : 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
matrix.transpose(): 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
np.transpose(matrix): 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
matrix.swapaxes(0, 1): 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
np.swapaxes(matrix, 0, 1): 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
matrix 데이터는 복사되지 않았습니다: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## flatten (행렬 펼치기)출력

In [15]:
# (5 , 4) 구조
data = [[1, 2, 3, 4], 
        [5, 6, 7, 8], 
        [9 ,10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]

matrix = np.array(data)

print(matrix.shape)
print(matrix.flatten())

# flatten() 함수를 사용해도 원래 matrix 2차원 배열은 자체는 변화가 없음.
print(matrix)

# flatten() 함수를 사용하면 1차원 배열로 변경 됨.
vec_flatten = matrix.flatten()
print(vec_flatten.ndim)
print(vec_flatten)

(5, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 산술 연산 및 선형대수(1) 출력

In [16]:
# (3, 3)
matrix_1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_2 = np.array([[2, 4, 6],
                     [8, 10, 12],
                     [14, 16, 18]])

# 2차원 배열에 사칙 연산 계산
print(matrix_1 + 2)
print(matrix_1 - 2)
print(matrix_1 / 2)
print(matrix_1 * 2)

# 2차원 배열끼리 사칙 연산 계산
print(matrix_1 + matrix_2)
print(matrix_1 - matrix_2)
print(matrix_1 / matrix_2)
print(matrix_1 * matrix_2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


## 산술 연산 및 선형대수(2) 출력

In [17]:
# (3, 3)
matrix_1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_2 = np.array([[2, 4, 6],
                     [8, 10, 12],
                     [14, 16, 18]])

# (3, 0)의 벡터를 더하는 경우
print(matrix_1 + [10, 10, 10])

# (3 , 1)의 벡터를 더하는 경우
print(matrix_1 + [[10], [10], [10]])


# 행렬의 덧셈과 뺄셈
# add와 subtract 함수 사용
print(np.add(matrix_1, matrix_2))
print(np.subtract(matrix_1, matrix_2))

# 행렬의 곱셈
# dot 사용
print(np.dot(matrix_1, matrix_2))

# @ 연산자 사용 가능 파이썬 3.5 이상 버전가능
print(matrix_1 @ matrix_2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


## 배열 간의 비교 연산 출력

In [18]:
# (3, 3)
matrix_1 = np.array([[1, 4, 13],
                     [4, 5, 16],
                     [7, 16, 19]])

matrix_2 = np.array([[1, 4, 6],
                     [8, 5, 12],
                     [14, 16, 9]])
# 배열 간의 비교 연산
print(matrix_1 > matrix_2)
print(matrix_1 >= matrix_2)
print(matrix_1 == matrix_2)
print(matrix_1 != matrix_2)
print(matrix_1 < matrix_2)
print(matrix_1 <= matrix_2)

# 반환된 불리언 배열을 index(색인)으로 하여 해당 요소값 확인
print(matrix_1[matrix_1 > matrix_2])
print(matrix_1[matrix_1 >= matrix_2])
print(matrix_1[matrix_1 == matrix_2])
print(matrix_1[matrix_1 != matrix_2])
print(matrix_1[matrix_1 < matrix_2])
print(matrix_1[matrix_1 <= matrix_2])

[[False False  True]
 [False False  True]
 [False False  True]]
[[ True  True  True]
 [False  True  True]
 [False  True  True]]
[[ True  True False]
 [False  True False]
 [False  True False]]
[[False False  True]
 [ True False  True]
 [ True False  True]]
[[False False False]
 [ True False False]
 [ True False False]]
[[ True  True False]
 [ True  True False]
 [ True  True False]]
[13 16 19]
[ 1  4 13  5 16 16 19]
[ 1  4  5 16]
[13  4 16  7 19]
[4 7]
[ 1  4  4  5  7 16]


## 불리언(Boolean)값으로 인덱싱 출력

In [19]:
# (10, )
# 1차원 배열을 만듭니다.
vector_1 = np.array([70, 71.3, 72.1, 73, 68, 59, 55, 66, 60, 80])
vector_2 = np.array(["하준", "도윤", "준우", "지호", "제균", "시우", "주원", "민준", "지현", "봉기"])

# True, False로 값들을 리턴합니다.
result_bool = vector_1 > 70
print(result_bool)

# 리턴된 True, False 값을 인덱스 값으로 데이터를 조회 합니다.
print(vector_2[result_bool])

[False  True  True  True False False False False False  True]
['도윤' '준우' '지호' '봉기']
